Always call onPostDeactivate even if focus not returned
focus-trap/focus-trap pull request #433
Opened 2021-06-16 17:39 UTC by stefcameron

This is consistent with always calling onPostActivate after
onActivate.

I enhanced the Animated Trigger demo to show that
onPostDeactivate is always called even if `returnFocus`
is not set.

And I added visible (i.e. on-screen) messages for
the Animated Dialog and Animated Trigger demos
instead of logging to the console. This way, I could
add a test for the Tigger where focus is not returned
but onPostDeactivate is still called.

<details>
<summary>PR Checklist</summary>
<br/>

__Please leave this checklist in your PR.__

- Source changes maintain stated browser compatibility.
- Includes updated `/docs/demo-bundle.js` if source or docs code was changed.
- Issue being fixed is referenced.
- Unit test coverage added/updated.
- E2E test coverage added/updated.
- Typings added/updated.
- README updated (API changes, instructions, etc.).
- Changes to dependencies explained.
- Changeset added (run `yarn changeset` locally to add one, and follow the prompts).
  - EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it will not affect package consumers.

</details>

2021-06-16 18:08 UTC, stefcameron commented on docs/demo-bundle.js
> -        if (returnFocus) {
Ignore this file, it's generated from `yarn demo-bundle`

2021-06-16 18:08 UTC, stefcameron commented
@Dan503 Please check this out when you have a moment.

2021-06-17 21:25 UTC, Dan503 commented
I haven't forgotten about this. I just haven't had a chance to review yet.

2021-06-18 10:40 UTC, Dan503 reviewed
I've made some code suggestions in this PR (I don't have permission to push to your PR)

https://github.com/focus-trap/focus-trap/pull/434

2021-06-18 10:42 UTC, Dan503 requested changes
Sorry, I was supposed to check the "Request changes" radio button.

2021-06-18 14:03 UTC, stefcameron commented on docs/index.html
> +        (i.e. <code>onPostActivate</code>), a &quot;trap activated&quot; message appears next to the Activate button.
Force of habit from React always complaining about using characters like the apostrophe instead of `&apos;` for example.

2021-06-18 15:08 UTC, Dan503 approved these changes

2021-06-18 15:20 UTC, merged